formatting:
  active: true
  android: false
  autoCorrect: true
  MaximumLineLength:
    active: false
  Indentation:
    active: true
  NoEmptyFirstLineInMethodBlock:
    active: true
  AnnotationOnSeparateLine:
    active: true
